### PR TITLE
Fix "tipsy-ness" level selector on mobile

### LINKED ISSUE #16: Fix "tipsy-ness" level selector on mobile
As described in #14, the tipsy-ness level selector doesn't work very well on mobile devices.

### PR DESCRIPTION
**Pull request by Quaffel**
Fix adds the previously missing "touchmove" event listener to the selector's container. As the default input handling must be suppressed (`Event#preventDefault`), regular DOM event listeners are registered manually as React always uses passive event listeners (which are not allowed to invoke this function) for handling these events ([PR](https://github.com/facebook/react/pull/19654)).

If there's a more elegant/state-of-the-art solution, please let me know.

Resolves #16.

### CODE REVIEW

**Comment by Jonasdoubleyou** [comment]
Seems reasonable as long as https://github.com/facebook/react/issues/6436 stays open.

File: frontend/src/tipsyselector/circleselector.tsx [hunk 1]
```diff
@@ -147,7 +153,24 @@ export function CircleSelector({
...
+
+        // Necessary as event listeners must not be passive (Event#preventDefault fails otherwise)
+        element.addEventListener("mousemove", onMove, { passive: false });
+        element.addEventListener("touchmove", onMove, { passive: false });
+
+        return () => {
+            element.removeEventListener("mousemove", onMove);
+            element.removeEventListener("touchmove", onMove);
+        }
+    });
```
Comment (Jonasdoubleyou) [inline frontend/src/tipsyselector/circleselector.tsx:171]: missing dependency `containerRef`

**Review by Jonasdoubleyou — CHANGES_REQUESTED** [review]

**Review by Jonasdoubleyou — APPROVED** [review]

**Comment by Jonasdoubleyou** [comment]
Assuming that `setValue` is stable, omitting `onMove` from dependencies is okay :) (another option would be to wrap `onMove´ in a `useCallback`, but yeah, works this way too for me ...)

**Comment by Quaffel** [comment]
Haven't thought of this, thank you for the heads-up! The assumption that `setValue` is stable is quite fair to make, but using `useCallback` would have been better; you're right. I won't open a separate pull request for this though.
